version: 0.2
phases:
  build:
    commands:
      - echo "This is build phase...zipping my webpage ..hurrey"
      
    post_build:
      commands:
        - echo "Deployed to S3" 
artifacts:
  files:
    - '**/*'
